name = "flying-fish"
author = "macuguita"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdba29199274baa6ca2eb3cade51ce737992bd11c62fb02302fc891c84c1d0d8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
unsup = "1.2.0"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapack/required"
