name = "flying-fish"
author = "macuguita"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "531ebc793148ac99213cb600d5037d2276b72d7e153cf5f961e9e343342ff790"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
unsup = "1.2.0"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapack/required"
