name = "flying-fish"
author = "macuguita"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "705964811c301ac7aeaef567d5a8fb98bda602cfb98ab3808df81ebfba8cb90f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
unsup = "1.2.0"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapack/required"
